version: '3'

services:
  mc-panel.app:
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    build: ./docker
    image: mc-panel-dev
    volumes:
      - ./www:/var/www
      - /home/${SHELL_USER}/minecraft_server:/var/minecraft_server
    ports:
      - ${CONTAINER_PORT}:80
      - 8000:8000
    networks:
      - mc-panel
    env_file:
      - .env

  mc-panel.mysql:
    container_name: ${MYSQL_HOST}
    restart: unless-stopped
    image: mysql:5.6
    networks: 
      - mc-panel
    env_file:
      - .env

networks:
  mc-panel:
    driver: bridge