version: '3'

services:
  app:
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    build: ./docker
    image: mc-panel-dev
    volumes:
      - ./www:/var/www
      - /home/${SHELL_USER}/minecraft_server:/var/minecraft_server
    ports:
      - ${CONTAINER_PORT}:80
    networks:
      - mc-panel
    env_file:
      - .env

  mysql:
    container_name: ${HOST_MYSQL}
    restart: unless-stopped
    image: mariadb
    networks: 
      - mc-panel
    env_file:
      - .env

  mailcatcher:
    container_name: ${CONTAINER_MAIL}
    restart: unless-stopped
    image: schickling/mailcatcher
    ports:
      - ${CONTAINER_MAIL_PORT}:1080
    networks:
      - mc-panel

networks:
  mc-panel:
    driver: bridge