#!/usr/bin/env php
<?php declare(strict_types=1);
if (php_sapi_name() != "cli") {
    fwrite(
        STDERR,
        PHP_EOL."File only in CLI".PHP_EOL
    );
    die(1);
}
require_once '/var/www/vendor/autoload.php';
$dbname = getenv('MYSQL_DATABASE');
$dbuser = getenv('MYSQL_USER');
$dbpassword = getenv('MYSQL_PASSWORD');
$dbhost = getenv('MYSQL_HOST');
$NUM_OF_ATTEMPTS = 10;
$attempts = 0;
do {
    try
    {
        $pdo = new PDO("mysql:host=$dbhost;dbname=$dbname", $dbuser, $dbpassword);
    } catch (Exception $e) {
        $attempts++;
        sleep(3);
        continue;
    }
    break;
} while ($attempts < $NUM_OF_ATTEMPTS);
$prefix = getenv('PREFIX');
echo "Creating Database".PHP_EOL;
sleep(1);
echo "[||";
$pdo->exec("DROP TABLE `{$prefix}server`");
$pdo->exec("DROP TABLE `{$prefix}user`");
$pdo->exec("DROP TABLE `{$prefix}role`");
$pdo->exec("DROP TABLE `{$prefix}permissions`");
echo "||";
$pdo->exec("CREATE TABLE `{$prefix}server` (
    `id`            int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `name`          varchar(255) NOT NULL,
    `panel_port`    smallint(3) UNSIGNED NOT NULL,
    `is_installed`  tinyint(1) UNSIGNED NOT NULL,
    `status`        tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
    `version`       varchar(255) NOT NULL,
    PRIMARY KEY(`id`)
)");
echo "||";
$pdo->exec("CREATE TABLE `{$prefix}user` (
    `id`        int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `username`  varchar(255) NOT NULL,
    `password`  varchar(255) NOT NULL,
    `role_id`   tinyint(1) UNSIGNED NOT NULL,
    PRIMARY KEY(`id`)
)");
echo "||";
$pdo->exec("CREATE TABLE `{$prefix}role` (
    `id`        tinyint(1) UNSIGNED NOT NULL AUTO_INCREMENT,
    `role_name` varchar(255) NOT NULL DEFAULT 2,
    PRIMARY KEY(`id`)
)");
echo "||";
$pdo->exec("CREATE TABLE `{$prefix}permissions` (
    `id`                 int(11) unsigned NOT NULL AUTO_INCREMENT,
    `user_id`            int(11) unsigned NOT NULL,
    `start_and_stop`     tinyint(1) unsigned NOT NULL DEFAULT 1,
    `change_version`     tinyint(1) unsigned NOT NULL DEFAULT 1,
    `send_command`       tinyint(1) unsigned NOT NULL DEFAULT 1,
    `plugins`            tinyint(1) unsigned NOT NULL DEFAULT 1,
    `config`             tinyint(1) unsigned NOT NULL DEFAULT 1,
    `worlds_management`   tinyint(1) unsigned NOT NULL DEFAULT 1,
    `players_management` tinyint(1) unsigned NOT NULL DEFAULT 1,
    `scheduled_tasks`    tinyint(1) unsigned NOT NULL DEFAULT 1,
    `file_export`        tinyint(1) unsigned NOT NULL DEFAULT 1,
    `co_admin`           tinyint(1) unsigned NOT NULL DEFAULT 1,
    PRIMARY KEY(`id`)
)");
echo "||||";
$pdo->exec('SET FOREIGN_KEY_CHECKS = 0');
$pdo->exec("TRUNCATE TABLE `{$prefix}server`");
$pdo->exec("TRUNCATE TABLE `{$prefix}user`");
$pdo->exec("TRUNCATE TABLE `{$prefix}role`");
$pdo->exec("TRUNCATE TABLE `{$prefix}permissions`");
$pdo->exec('SET FOREIGN_KEY_CHECKS = 1');
echo "||]".PHP_EOL;
echo "Instert default value to the database".PHP_EOL;
sleep(1);
echo "[||";
// Check what is the last minecraft version
$json = file_get_contents('https://pastebin.com/raw/LVdci0Ck');
$versions = json_decode($json, true);
$version = array_key_first($versions['vanilla']['stable']);
$pdo->exec("INSERT INTO `{$prefix}server` (
    `name`, `panel_port`, `is_installed`, `status`, `version`
) VALUES (
    'Minecraft Panel', 8080, 0, 0, 'MC_{$version}'
)");
echo "||||";
$pdo->exec("INSERT INTO `{$prefix}role` (
    `role_name`
) VALUES 
    ('admin'),
    ('co-admin'),
    ('moderator')
");
echo "||||";
$pdo->exec("INSERT INTO `{$prefix}permissions` (
    `user_id`
) VALUES
    ('1')
");
$passwordHash = password_hash('admin', PASSWORD_ARGON2ID);
$pdo->exec("INSERT INTO `{$prefix}user` (
    `username`, `password`, `role_id`
) VALUES (
    'admin', '{$passwordHash}', 1
)");
echo "||]".PHP_EOL;