#!/usr/bin/env php
<?php

declare(strict_types=1);
if (php_sapi_name() != "cli") {
    fwrite(
        STDERR,
        PHP_EOL . "File only in CLI" . PHP_EOL
    );
    die(1);
}

require_once '/var/www/vendor/autoload.php';

$prefix = getenv('PREFIX');
$dbname = getenv('MYSQL_DATABASE');
$dbuser = getenv('MYSQL_USER');
$dbpassword = getenv('MYSQL_PASSWORD');
$dbhost = getenv('MYSQL_HOST');
$NUM_OF_ATTEMPTS = 10;
$attempts = 0;
do {
    try {
        $pdo = new PDO("mysql:host=$dbhost;dbname=$dbname", $dbuser, $dbpassword);
    } catch (Exception $e) {
        $attempts++;
        sleep(3);
        continue;
    }
    break;
} while ($attempts < $NUM_OF_ATTEMPTS);

class progressBar
{

    private int $total;

    public function __construct(int $total)
    {
        $this->total = $total;
    }

    function done(int $done, string $info = "", int $width = 50)
    {
        $perc = round(($done * 100) / $this->total);
        $bar = (int) round(($width * $perc) / 100);
        return sprintf("\e[32m %s%%\e[0m[\e[32m%s>%s\e[0m]%s\r", $perc, str_repeat("=", $bar), str_repeat(" ", $width - $bar), $info . "\e[0m");
    }
}

$barCreate = new progressBar(7);
echo "\e[1m\e[33m Creating Database\e[0m" . PHP_EOL;
sleep(1);

echo $barCreate->done(1);
$pdo->exec("DROP TABLE `{$prefix}server`");
$pdo->exec("DROP TABLE `{$prefix}user`");
$pdo->exec("DROP TABLE `{$prefix}role`");
$pdo->exec("DROP TABLE `{$prefix}permissions`");

echo $barCreate->done(2);
$pdo->exec("CREATE TABLE `{$prefix}server` (
    `id`            int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `name`          varchar(255) NOT NULL,
    `status`        tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
    `version`       varchar(255) NOT NULL,
    PRIMARY KEY(`id`)
)");

echo $barCreate->done(3);
$pdo->exec("CREATE TABLE `{$prefix}user` (
    `id`        int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `username`  varchar(255) NOT NULL,
    `password`  varchar(255) NOT NULL,
    `role_id`   tinyint(1) UNSIGNED NOT NULL,
    `default_password`   tinyint(1) UNSIGNED NOT NULL DEFAULT 1,
    PRIMARY KEY(`id`)
)");

echo $barCreate->done(4);
$pdo->exec("CREATE TABLE `{$prefix}role` (
    `id`        tinyint(1) UNSIGNED NOT NULL AUTO_INCREMENT,
    `role_name` varchar(255) NOT NULL DEFAULT 2,
    PRIMARY KEY(`id`)
)");

echo $barCreate->done(5);
$pdo->exec("CREATE TABLE `{$prefix}permissions` (
    `id`                 int(11) unsigned NOT NULL AUTO_INCREMENT,
    `user_id`            int(11) unsigned NOT NULL,
    `start_and_stop`     tinyint(1) unsigned NOT NULL DEFAULT 1,
    `change_version`     tinyint(1) unsigned NOT NULL DEFAULT 1,
    `send_command`       tinyint(1) unsigned NOT NULL DEFAULT 1,
    `plugins`            tinyint(1) unsigned NOT NULL DEFAULT 1,
    `config`             tinyint(1) unsigned NOT NULL DEFAULT 1,
    `worlds_management`   tinyint(1) unsigned NOT NULL DEFAULT 1,
    `players_management` tinyint(1) unsigned NOT NULL DEFAULT 1,
    `scheduled_tasks`    tinyint(1) unsigned NOT NULL DEFAULT 1,
    `file_export`        tinyint(1) unsigned NOT NULL DEFAULT 1,
    `co_admin`           tinyint(1) unsigned NOT NULL DEFAULT 1,
    PRIMARY KEY(`id`)
)");

echo $barCreate->done(6);
$pdo->exec('SET FOREIGN_KEY_CHECKS = 0');
$pdo->exec("TRUNCATE TABLE `{$prefix}server`");
$pdo->exec("TRUNCATE TABLE `{$prefix}user`");
$pdo->exec("TRUNCATE TABLE `{$prefix}role`");
$pdo->exec("TRUNCATE TABLE `{$prefix}permissions`");
$pdo->exec('SET FOREIGN_KEY_CHECKS = 1');
echo $barCreate->done(7) . PHP_EOL;
echo "" . PHP_EOL;

$barInsert = new progressBar(4);
echo "\e[1m\e[33m Instert default value to the database\e[0m" . PHP_EOL;
sleep(1);

echo $barInsert->done(1);
// Check what is the last minecraft version
$versions = json_decode(file_get_contents("https://launchermeta.mojang.com/mc/game/version_manifest.json"), true);
$version = $versions['latest']['release'];
$pdo->exec("INSERT INTO `{$prefix}server` (
    `name`, `status`, `version`
) VALUES (
    'Minecraft Panel', 0, 'Release_{$version}'
)");

echo $barInsert->done(2);
$pdo->exec("INSERT INTO `{$prefix}role` (
    `role_name`
) VALUES 
    ('admin'),
    ('co-admin'),
    ('moderator')
");

echo $barInsert->done(3);
$pdo->exec("INSERT INTO `{$prefix}permissions` (
    `user_id`
) VALUES
    ('1')
");
$passwordHash = password_hash('admin', PASSWORD_ARGON2ID);
$pdo->exec("INSERT INTO `{$prefix}user` (
    `username`, `password`, `role_id`
) VALUES (
    'admin', '{$passwordHash}', 1
)");

echo $barInsert->done(4) . PHP_EOL;
echo "" . PHP_EOL;
